/**
 * Resume optimization route.
 * POST /api/optimize
 *
 * Accepts: { resume, jobDescription, tier }
 *   - tier 'basic': proofread & format
 *   - tier 'pro': keyword optimization + full rewrite + cover letter
 *
 * Uses OpenAI (via ai service) if OPENAI_API_KEY is set.
 * Falls back to mock data when the API key isn't configured.
 */

import { Router } from 'express';
import { optimizeResume, generateCoverLetter, extractKeywords } from '../services/ai.js';

export const optimizeRouter = Router();

optimizeRouter.post('/', async (req, res) => {
  try {
    const { resume, jobDescription, tier = 'basic' } = req.body;

    if (!resume || !jobDescription) {
      return res.status(400).json({ error: 'Resume and job description are required' });
    }

    if (!['basic', 'pro'].includes(tier)) {
      return res.status(400).json({ error: 'Tier must be "basic" or "pro"' });
    }

    const hasApiKey = process.env.OPENAI_API_KEY && process.env.OPENAI_API_KEY.startsWith('sk-');

    if (hasApiKey) {
      // === REAL AI MODE ===
      const result = { tier, keywords: extractKeywords(jobDescription) };

      if (tier === 'basic') {
        result.optimizedResume = await optimizeResume(resume, jobDescription, 'basic');
      } else {
        // Pro tier: keyword optimization + full rewrite + cover letter
        const [keywordOptimized, rewrittenResume, coverLetter] = await Promise.all([
          optimizeResume(resume, jobDescription, 'keyword'),
          optimizeResume(resume, jobDescription, 'rewrite'),
          generateCoverLetter(resume, jobDescription, extractCompanyName(jobDescription)),
        ]);
        result.optimizedResume = rewrittenResume;
        result.keywordOptimized = keywordOptimized;
        result.optimizedCoverLetter = coverLetter;
      }

      res.json(result);
    } else {
      // === MOCK FALLBACK MODE ===
      console.log('OPENAI_API_KEY not set — returning mock result');
      const result = generateMockResult(resume, jobDescription, tier);
      res.json(result);
    }
  } catch (err) {
    console.error('Optimize error:', err);
    res.status(500).json({ error: 'Failed to optimize resume. Please check your API key and try again.' });
  }
});

/**
 * Extract a company name from a job description (basic heuristic)
 */
function extractCompanyName(jobDesc) {
  const match = jobDesc.match(/(?:at|for|with)\s+([A-Z][A-Za-z0-9\s&.]+?)(?:\s+is\s+|\s+are\s+|\s+we\s+|,|\n|$)/);
  return match ? match[1].trim() : '[Company Name]';
}

/**
 * Mock fallback result when no API key is configured
 */
function generateMockResult(resume, jobDesc, tier) {
  const keywords = extractKeywords(jobDesc);

  const optimizedResume = tier === 'pro'
    ? `[PRO OPTIMIZED]\n\n${resume}\n\n--- Optimized for keywords: ${keywords.slice(0, 10).join(', ')} ---`
    : `${resume}\n\n--- Keywords to emphasize: ${keywords.slice(0, 8).join(', ')} ---`;

  const result = {
    optimizedResume,
    keywords,
    matchScore: Math.floor(Math.random() * 30) + 60,
    tier,
  };

  if (tier === 'pro') {
    result.optimizedCoverLetter = `Dear Hiring Manager,\n\nI am writing to express my interest in this position. Based on the job description, I understand you are looking for someone with skills in ${keywords.slice(0, 5).join(', ')}.\n\n[Full cover letter will be generated by AI when OPENAI_API_KEY is set]\n\nSincerely,\n[Your Name]`;
  }

  return result;
}
